FROM node:24-alpine
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN CI=true pnpm install --frozen-lockfile
COPY . .
EXPOSE 3000
ENV HOSTNAME=0.0.0.0
CMD ["pnpm", "dev"]
